#!/bin/sh

GIT_TAGS=".git/tags"
GIT_TAGS_LOCK=".git/tags.lock"

if [ -f $GIT_TAGS_LOCK ]; then
    exit 0
fi

touch $GIT_TAGS_LOCK

if [ -f $GIT_TAGS ]; then
    rm -f $GIT_TAGS
fi

if [ -x "$(command -v ctags)" ]; then
    ctags --tag-relative -Rf${GIT_TAGS} \
          --exclude="*.map.js" \
          --exclude="*.min.js" \
          --exclude=".git" \
          --exclude=".bin" \
          --exclude="bin" \
          --exclude="node_modules/**/demos" \
          --exclude="node_modules/**/demo" \
          --exclude="node_modules/**/dist" \
          --exclude="node_modules/**/docs" \
          --exclude="node_modules/**/doc" \
          --exclude="node_modules/**/min" \
          --exclude="node_modules/**/node_modules" \
          --exclude="node_modules/**/locales" \
          --exclude="node_modules/**/locale" \
          --exclude="public" \
          --exclude="storage" \
          --exclude="tests" \
          --exclude="test" \
          --exclude="vendor/**/*.js"
else
    echo "ERR: ctags not installed" 2>&1
    exit 0
fi

if [ -f $GIT_TAGS_LOCK ]; then
    rm -f $GIT_TAGS_LOCK
fi

