alias usvpn="sudo openconnect -bqu ir317288 --no-cert-check us5.cisadd2.com"
alias usvpn2="sudo openconnect -bqu ir317288 --no-cert-check us2.cisadd2.com"
alias ukvpn="sudo openconnect -bqu ir317288 --no-cert-check uk.cisadd2.com"
alias cavpn="sudo openconnect -bqu ir317288 --no-cert-check ca.cisadd2.com"
alias frvpn="sudo openconnect -bqu ir317288 --no-cert-check fr.cisadd2.com"
alias devpn="sudo openconnect -bqu ir317288 --no-cert-check de.cisadd2.com"

alias usvpn800="sudo openconnect -bqu ir317288 --no-cert-check us2.cisadd3.com:800"
alias ukvpn800="sudo openconnect -bqu ir317288 --no-cert-check uk.cisadd3.com:800"
alias cavpn800="sudo openconnect -bqu ir317288 --no-cert-check ca.cisadd3.com:800"
alias frvpn800="sudo openconnect -bqu ir317288 --no-cert-check fr.cisadd3.com:800"
alias devpn800="sudo openconnect -bqu ir317288 --no-cert-check de.cisadd3.com:800"

alias a="php ./artisan"
alias c="php composer.phar"
alias phpunit="./vendor/bin/phpunit"

alias gstat="git status"
alias gadd="git add"
alias gaddp="git add -p"
alias gcomm="git commit -m"
alias grest="git reset"
alias greha="git reset --hard"
alias gfech="git fetch"
alias gpull="git pull"
alias gpush="git push"
alias greba="git rebase"
alias gdiff="git diff"
alias glog="git log --oneline"
alias glogg="git log --oneline --decorate --graph --all"
alias gcout="git checkout"
alias gbrch="git branch"
alias gnbrc="git checkout -b"
alias grbrc="git branch --remote"
alias gabrc="git branch --all"
alias gtag="git tag"
alias gatag="git tag --all"

alias vimrc="vim ~/.vimrc"
alias clip="xclip -selection clipboard"

