" vim: et ts=2 sts=2 sw=2 fdm=marker fdl=1
" colors {{{2
set term=xterm
set t_Co=256
set cursorline
colorscheme shine

" read/write {{{2
set encoding=utf-8
set fileencoding=utf-8
set fileformat=unix
scriptencoding utf-8

" spelling {{{2
set spelllang=en,fa
set spellfile=~/.vim/spell/en.utf-8.add,~/.vim/spell/fa.utf-8.add

" search {{{2
set hlsearch
set ignorecase
set incsearch
set smartcase

" split {{{2
set splitbelow
set splitright

" indentation {{{2
set autoindent
filetype plugin indent on
syntax enable

" undo {{{2
set undofile
set undodir=$HOME/.vim/undo
set undolevels=1000
set undoreload=10000

" vim backward-compatiblity {{{2
set shell=/bin/bash
set nobackup
set noshowmode
set noswapfile

" misc {{{2
set nohidden
set pastetoggle=<f2>
set updatetime=1250
set mouse=
set fdl=999
set scrolloff=8
set sidescroll=8

" autocmd group {{{2
augroup vimrc
  autocmd!
augroup END

" leader {{{2
let g:mapleader = "\<Space>"
let g:maplocalleader = 'm'

" terminal configs {{{2
autocmd vimrc TerminalOpen * if &buftype == 'terminal' | setlocal signcolumn=no nonumber | endif

" YAML specific configs {{{2
autocmd vimrc FileType yml,yaml setlocal softtabstop=2 shiftwidth=2 expandtab foldmethod=indent

" python specific configs {{{2
autocmd vimrc FileType python setlocal foldmethod=indent

" jump to the last position when reopening a file {{{2
autocmd vimrc BufReadPost * if line("'\"") > 0 && line("'\"") <= line("$") | exe "normal! g'\"" | endif

" Highlight VCS conflict markers {{{2
match ErrorMsg '^\(<\|=\|>\)\{7\}\([^=].\+\)\?$'

" custom mappings {{{2
nnoremap <cr> :noh<cr><cr>
nnoremap Y y$
inoremap jk <esc>

" smart movement {{{3
nnoremap gj j
nnoremap gk k
vnoremap gj j
vnoremap gk k

nnoremap j gj
nnoremap k gk
vnoremap j gj
vnoremap k gk

" center the cursor {{{3
nnoremap n nzz
nnoremap N Nzz
nnoremap g; g;zz
nnoremap g, g,zz
nnoremap <c-o> <c-o>zz

" write as sudo {{{3
cmap w!! w !sudo tee > /dev/null % <cr> :edit!<cr>
