# Path to your oh-my-zsh installation.
export ZSH="/home/shahin/.zsh"
case $PATH in
    *"$HOME/.local/bin"*) ;;
    *) PATH="$HOME/.local/bin:$PATH" ;;
esac
case $PATH in
    *"$HOME/.yarn/bin"*) ;;
    *) PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH" ;;
esac
case $PATH in
    *"$HOME/.cargo/bin"*) ;;
    *) PATH="$HOME/.cargo/bin:$PATH" ;;
esac
export PATH

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
ZSH_THEME="jnrowe"

# Set list of themes to pick from when loading at random
# Setting this variable when ZSH_THEME=random will cause zsh to load
# a theme from this variable instead of looking in ~/.oh-my-zsh/themes/
# If set to an empty array, this variable will have no effect.
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
 HIST_STAMPS="yyyy-mm-dd"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load?
# Standard plugins can be found in ~/.oh-my-zsh/plugins/*
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(
  artisan
  autojump
  colored-man-pages
  colorize
  # command-not-found
  common-aliases
  composer
  docker
  docker-compose
  # thefuck
  git
  gitignore
  node
  privoxy
  ssh-agent
  systemd
  tmux
  vi-mode
  vue
  yarn
  zsh-autosuggestions
  zsh-syntax-highlighting
)

if [ -z "$SSH_CLIENT" ] && [ -z "$SSH_TTY" ]; then
  ZSH_TMUX_AUTOSTART=true
fi

ZSH_TMUX_AUTOSTART_ONCE=true
ZSH_TMUX_AUTOQUIT=false
ZSH_TMUX_UNICODE=true

export TERM=xterm-256color
[ -n "$TMUX" ] && export TERM=screen-256color

source $ZSH/custom-omz.sh
# source $ZSH/plugins/zsh-you-should-use/you-should-use.plugin.zsh

# User configuration
[[ -s /etc/profile.d/autojump.sh ]] && . /etc/profile.d/autojump.sh
[[ -s ~/.autojump/etc/profile.d/autojump.sh ]] && . ~/.autojump/etc/profile.d/autojump.sh

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
export BROWSER='firefox'
export EDITOR='vim'

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
export SSH_KEY_PATH="~/.ssh/rsa_id"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.

# Remove the history (fc -l) command from the history list when invoked.
setopt histnostore
# Remove superfluous blanks from each command line being added to the history list.
setopt histreduceblanks

# keep a reasonable history size
HISTSIZE=1000
SAVEHIST=1000

export GPG_TTY=$(tty)
export GROFF_NO_SGR=1
export LESS=-XR

if [ -d "$HOME"/.zcompletion.d ]; then
    for F in "$HOME"/.zcompletion.d/*.zsh; do
        [ -f "$F" ] && source "$F"
    done
fi

if [ -e /run/privoxy.pid ]; then
    connect_privoxy
fi
