[theme]
name = "plain"

[icons]
name = "awesome5"

[icons.overrides]
net_down = "\uf063"
net_up = "\uf062"

[[block]]
block = "focused_window"
max_width = 50
show_marks = "all"

[[block]]
block = "music"

[[block]]
block = "disk_space"
info_type = "available"
path = "/"
format = "{path} {available}"
unit = "GB"
interval = 60
warning = 50.0
alert = 20.0

[[block]]
block = "disk_space"
path = "/home"
info_type = "available"
format = "{path} {available}"
unit = "GB"
interval = 60
warning = 30.0
alert = 10.0

[[block]]
block = "net"
device = "wlp0s20f3"
hide_missing = true
hide_inactive = true

[[block]]
block = "net"
device = "enp7s0"
hide_missing = true
hide_inactive = true

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_avail;M}/{mem_total;M}"
clickable = false

[[block]]
block = "load"
interval = 2
format = "{5m}"
info = 5.9
warning = 8.9
critical = 11.9
