[theme]
name = "plain"
[theme.overrides]
separator = "|"

[icons]
name = "awesome5"

[icons.overrides]
net_down = "\uf063"
net_up = "\uf062"

[[block]]
block = "disk_space"
info_type = "available"
unit = "GB"
interval = 60
warning = 50.0
alert = 20.0

[[block]]
block = "disk_space"
path = "/home"
alias = "/home"
info_type = "available"
unit = "GB"
interval = 60
warning = 30.0
alert = 10.0

[[block]]
block = "net"
device = "wlp0s20f3"
speed_digits = 2
use_bits = false
hide_missing = true
hide_inactive = true

[[block]]
block = "net"
device = "enp7s0"
speed_digits = 2
use_bits = false
hide_missing = true
hide_inactive = true

# [[block]]
# block = "custom"
# on_click = "zsh ~/.bin/vpn/checkvpn.sh toggle"
# command = "zsh ~/.bin/vpn/checkvpn.sh"
# json = true
# interval = 5

[[block]]
block = "memory"
display_type = "memory"
clickable = true
format_mem = "{MAm} MB"

[[block]]
block = "load"
interval = 2
format = "{5m}"
info = 5.9
warning = 8.9
critical = 11.9
