[theme]
name = "plain"
[theme.overrides]
separator = ""

[icons]
name = "awesome5"
[icons.overrides]
net_down = "\uf063"
net_up = "\uf062"
memory_mem = " "
cogs = " "
net_wireless = " W:"
net_wired = " E:"

[[block]]
block = "disk_space"
info_type = "available"
unit = "GB"
interval = 60
warning = 40.0
alert = 20.0

[[block]]
block = "disk_space"
path = "/hdd"
alias = "/hdd"
info_type = "available"
unit = "GB"
interval = 60
warning = 20.0
alert = 10.0

[[block]]
block = "net"
device = "wlo1"
speed_digits = 2
use_bits = false
hide_missing = true
hide_inactive = true

[[block]]
block = "net"
device = "ens38s0"
speed_digits = 2
use_bits = false
hide_missing = true
hide_inactive = true

[[block]]
block = "custom"
on_click = "zsh ~/.bin/vpn/nordvpn.sh toggle"
command = "zsh ~/.bin/vpn/nordvpn.sh"
json = true
interval = 5

[[block]]
block = "memory"
display_type = "memory"
clickable = false
format_mem = "{MAm} MB"

[[block]]
block = "load"
interval = 2
format = "{5m}"
info = 1.9
warning = 2.9
critical = 3.9
